services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bookmarker:
    image: bookmarker
    build: .
    restart: no
    env_file: ".env"
    ports:
      - "8000:8000"
