version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080