name: Trigger Deployment

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Service to deploy
        options:
          - frontend
          - backend
      version:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEPLOYMENT_PAT }}
          script: |
            const repoOwner = "${{ secrets.REPO_DEPLOYMENT_OWNER }}";
            const repoName = "${{ secrets.REPO_DEPLOYMENT_NAME }}";

            const payload = {
              event_type: "bookmarker",
              client_payload: {
                service: "${{ github.event.inputs.service }}",
                version: "${{ github.event.inputs.version }}",
              },
            };

            const response = await github.rest.repos.createDispatchEvent({
              owner: repoOwner,
              repo: repoName,
              ...payload,
            });

            console.log("Dispatched event, status:", response.status);
