name: Trigger Deployment

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Service to deploy
        options:
          - frontend
          - backend
      version:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        run: |
          repo=${{ secrets.REPO_DEPLOYMENT }} 
          event_type="trigger-workflow" 
          service=${{ github.event.inputs.service }}"
          version="${{ github.event.inputs.version }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo/actions/workflows/$workflow_id/dispatches \
            -d "{\"ref\": \"main\", \"inputs\": {\"version\": \"$version\", \"version\": \"$version\"}}"
