name: Trigger Deployment

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Service to deploy
        options:
          - frontend
          - backend
      version:
        type: string

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment
        run: |
          repo=${{ secrets.REPO_DEPLOYMENT }} 
          event_type="trigger-workflow" 
          service=${{ github.event.inputs.service }}"
          version="${{ github.event.inputs.version }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW_ID/dispatches \
            -d '{"ref":"topic-branch","inputs":{"service": "frontend", "version": "0.0.1"}}'
