name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python --version
          pip --version
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
        working-directory: django

      - name: Copy environment
        run: |
          cp .env.dist .env
          echo "IS_CI=True" >> .env
        working-directory: django

      - name: Run Tests
        run: |
          echo "{}" > firebase-serviceaccount.json
          poetry run python manage.py test
        working-directory: django
